services:
  database-service:
    container_name: db-container
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meubanco"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    container_name: user-service
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      database-service:
        condition: service_healthy
    networks:
      - my_network
    env_file:
      - ./user/.env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - user-service
    networks:
      - my_network
    ports:
      - "80:80"

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
